---

services:
  grafana:
    image: "docker.io/grafana/grafana-oss:latest"
    container_name: "grafana"
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.c0d3v0y463.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME="Authentik SSO"
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=your_secret_here
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.c0d3v0y463.com/application/o/authorize/
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.c0d3v0y463.com/application/o/token/
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.c0d3v0y463.com/application/o/userinfo/
      - GF_AUTH_GENERIC_OAUTH_SCOPES="openid email profile"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      # Main Router
      - "traefik.http.routers.grafana-https.rule=Host(`grafana.c0d3v0y463.com`)"
      - "traefik.http.routers.grafana-https.entrypoints=websecure"
      - "traefik.http.routers.grafana-https.tls=true"
      - "traefik.http.routers.grafana-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana-https.middlewares=grafana-strip"

      # Middleware: Strip Prefix if Needed
      - "traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/"
      - "traefik.http.middlewares.grafana-strip.stripprefix.forceSlash=false"

      # Service
      - "traefik.http.routers.grafana-https.service=grafana-https-service"
      - "traefik.http.services.grafana-https-service.loadbalancer.server.port=3000"

    networks:
      - "frontend"
    restart: "unless-stopped"
    volumes:
      - "grafana-data:/var/lib/grafana"

networks:
  frontend:
    external: true

volumes:
  grafana-data:
    external: true
